In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.mean([12,4,3,24,53])

19.2

In [4]:
np.median([12,4,3,24,53])

12.0

In [5]:
np.max([12,4,3,24,53])

53

In [6]:
np.random.randint(1,10,5)

array([4, 6, 7, 7, 1])

In [7]:
np.random.randint(10,50,5)

array([49, 45, 19, 24, 15])

In [8]:
np.random.rand(3,2)

array([[0.17149786, 0.42700331],
       [0.66491651, 0.26616563],
       [0.8960796 , 0.67067336]])

In [9]:
# Array

In [11]:
x1 = np.array([23,54,13,66,34,65])

In [12]:
x1

array([23, 54, 13, 66, 34, 65])

In [15]:
x1.ndim

1

In [16]:
x2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [17]:
x2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
x2.ndim

2

In [20]:
x3 = np.array([[[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]]])

In [21]:
x3

array([[[  1,   2,   3,   4,   5],
        [ 10,  20,  30,  40,  50],
        [100, 200, 300, 400, 500]]])

In [22]:
x3.ndim

3

In [23]:
np.random.rand(3,2,4)

array([[[0.20289009, 0.75917348, 0.17852226, 0.47372561],
        [0.74506215, 0.27528319, 0.38586479, 0.32495802]],

       [[0.36188376, 0.15910625, 0.24833674, 0.27023418],
        [0.08389687, 0.13160273, 0.95833005, 0.97035063]],

       [[0.30561085, 0.45450692, 0.4156201 , 0.65340782],
        [0.1726089 , 0.39131466, 0.5817803 , 0.78819535]]])

In [24]:
np.random.rand(3,2)

array([[0.03221897, 0.76073709],
       [0.09845646, 0.04634279],
       [0.47461443, 0.16893792]])

In [25]:
np.random.rand(5,3)

array([[0.25138087, 0.24903873, 0.37091912],
       [0.80048047, 0.20022069, 0.6909278 ],
       [0.53008121, 0.86526852, 0.73725687],
       [0.26611555, 0.82713263, 0.93753713],
       [0.4693407 , 0.49919061, 0.73275449]])